openapi: 3.0.1
info:
  contact:
    email: info@seqera.io
    url: https://seqera.io
  description: Seqera Platform services API
  title: Seqera actions pipeline-secrets API
  version: 1.181.0
tags:
- description: Pipeline secrets in a user or workspace context
  name: pipeline-secrets
paths:
  /pipeline-secrets:
    get:
      description: Lists all available pipeline secrets in a user context. Append `?workspaceId` to list secrets in a workspace context.
      operationId: ListPipelineSecrets
      parameters:
      - description: Workspace numeric identifier
        in: query
        name: workspaceId
        schema:
          format: int64
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListPipelineSecretsResponse'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad request
        '403':
          description: Operation not allowed
      security:
      - BearerAuth: []
      summary: List pipeline secrets
      tags:
      - pipeline-secrets
    post:
      description: Creates a new pipeline secret in the user context. Append `?workspaceId` to create the secret in a workspace context.
      operationId: CreatePipelineSecret
      parameters:
      - description: Workspace numeric identifier
        in: query
        name: workspaceId
        schema:
          format: int64
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePipelineSecretRequest'
        description: Pipeline secret create request
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePipelineSecretResponse'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad request
        '403':
          description: Operation not allowed
      security:
      - BearerAuth: []
      summary: Create pipeline secret
      tags:
      - pipeline-secrets
  /pipeline-secrets/validate:
    get:
      description: Confirms the validity of the given pipeline secret name in a user context. Append `?name=<your_secret_name>`. Append `?workspaceId` to validate the name in a workspace context.
      operationId: ValidatePipelineSecretName
      parameters:
      - description: Workspace numeric identifier
        in: query
        name: workspaceId
        schema:
          format: int64
          type: integer
      - description: Secret name to validate
        in: query
        name: name
        schema:
          type: string
      responses:
        '204':
          description: OK - No content
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad request
        '403':
          description: Operation not allowed
        '409':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Duplicate element
      security:
      - BearerAuth: []
      summary: Validate secret name
      tags:
      - pipeline-secrets
  /pipeline-secrets/{secretId}:
    delete:
      description: Deletes the pipeline secret identified by the given `secretId`.
      operationId: DeletePipelineSecret
      parameters:
      - description: Secret numeric identifier
        in: path
        name: secretId
        required: true
        schema:
          format: int64
          type: integer
      - description: Workspace numeric identifier
        in: query
        name: workspaceId
        schema:
          format: int64
          type: integer
      responses:
        '204':
          description: OK - No content
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad request
        '403':
          description: Operation not allowed
      security:
      - BearerAuth: []
      summary: Delete secret
      tags:
      - pipeline-secrets
    get:
      description: Retrieves the details of the pipeline secret identified by the given `secretId`.
      operationId: DescribePipelineSecret
      parameters:
      - description: Secret numeric identifier
        in: path
        name: secretId
        required: true
        schema:
          format: int64
          type: integer
      - description: Workspace numeric identifier
        in: query
        name: workspaceId
        schema:
          format: int64
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribePipelineSecretResponse'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad request
        '403':
          description: Operation not allowed
      security:
      - BearerAuth: []
      summary: Describe pipeline secret
      tags:
      - pipeline-secrets
    put:
      description: Updates the pipeline secret identified by the given `secretId`.
      operationId: UpdatePipelineSecret
      parameters:
      - description: Secret numeric identifier
        in: path
        name: secretId
        required: true
        schema:
          format: int64
          type: integer
      - description: Workspace numeric identifier
        in: query
        name: workspaceId
        schema:
          format: int64
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePipelineSecretRequest'
        description: Secret update request
        required: true
      responses:
        '204':
          description: OK - No content
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad request
        '403':
          description: Operation not allowed
      security:
      - BearerAuth: []
      summary: Update secret
      tags:
      - pipeline-secrets
components:
  schemas:
    UpdatePipelineSecretRequest:
      properties:
        value:
          type: string
      type: object
    CreatePipelineSecretResponse:
      properties:
        secretId:
          format: int64
          type: integer
      type: object
    CreatePipelineSecretRequest:
      properties:
        name:
          type: string
        value:
          type: string
      type: object
    ListPipelineSecretsResponse:
      properties:
        pipelineSecrets:
          items:
            $ref: '#/components/schemas/PipelineSecret'
          type: array
        totalSize:
          format: int64
          type: integer
      type: object
    ErrorResponse:
      properties:
        message:
          type: string
      required:
      - message
      type: object
    DescribePipelineSecretResponse:
      properties:
        pipelineSecret:
          $ref: '#/components/schemas/PipelineSecret'
      type: object
    PipelineSecret:
      properties:
        dateCreated:
          format: date-time
          readOnly: true
          type: string
        id:
          format: int64
          nullable: true
          type: integer
        lastUpdated:
          format: date-time
          readOnly: true
          type: string
        lastUsed:
          format: date-time
          readOnly: true
          type: string
        name:
          maxLength: 100
          pattern: ^[a-zA-Z_](?:[0-9A-Za-z]+|(_)(?!\1)){1,49}$
          type: string
      required:
      - name
      type: object
  securitySchemes:
    BearerAuth:
      bearerFormat: jwt
      scheme: bearer
      type: http
